#
# Copyright (C) 2018 Nalej Group - All Rights Reserved
#

# iron/go is the alpine image with only ca-certificates added
FROM iron/go

# Now just add the binary\
RUN mkdir /nalej

# Now just add the binary
COPY networking /nalej/

ENTRYPOINT ["./nalej/networking"]