apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-network-manager
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-network-manager
    namespace: nalej
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
