kind: Service
apiVersion: v1
metadata:
  name: network-manager
  namespace: __NPH_NAMESPACE
  labels:
    cluster: management
    component: network-manager
spec:
  selector:
    cluster: management
    component: network-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: grpc
  - protocol: UDP
    port: 9993
    targetPort: 9993
    name: zt