apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cluster: management
    component: network-manager
  name: data-network-manager
  namespace: __NPH_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-premium
