###
# Application network-manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: network-manager
  name: network-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: network-manager
  template:
    metadata:
      labels:
        cluster: management
        component: network-manager
    spec:
      containers:
      - name: network-manager
        image: nalejregistry.azurecr.io/nalej/network-manager:VERSION
        imagePullPolicy: Always
        args:
          - "run"
          - "--dnsurl=http://dns-server-ui.nalej:80"
          - "--sm=system-model.nalej:8800"
          - "--zturl=http://localhost:9993"
          - "--debug"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: dev-net-tun
          readOnly: true
          mountPath: /dev/net/tun
        - name: data-network-manager
          mountPath: /var/lib/zerotier-one
        - name: zt-planet
          mountPath: /zt/planet
          readOnly: true
        - name: zt-identity-public
          mountPath: /zt/identity-public
          readOnly: true
        - name: zt-identity-secret
          mountPath: /zt/identity-secret
          readOnly: true
      imagePullSecrets:
      - name: nalej-registry
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
      - name: data-network-manager
        persistentVolumeClaim:
          claimName: data-network-manager
      - name: zt-planet
        secret:
          secretName: zt-planet
      - name: zt-identity-public
        secret:
          secretName: zt-identity-public
      - name: zt-identity-secret
        secret:
          secretName: zt-identity-secret