###
# Application network-manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: network-manager
  name: network-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: network-manager
  template:
    metadata:
      labels:
        cluster: management
        component: network-manager
    spec:
      containers:
      - name: example
        image: nalej/network-manager:VERSION
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: myregistrykey
