kind: Service
apiVersion: v1
metadata:
  name: network-manager
  namespace: nalej
  labels:
    cluster: management
    component: network-manager
spec:
  selector:
    cluster: management
    component: network-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000