###
# Application network-manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: network-manager
  name: network-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: network-manager
  template:
    metadata:
      labels:
        cluster: management
        component: network-manager
    spec:
      containers:
        - name: network-manager
          image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/network-manager:__NPH_VERSION
          imagePullPolicy: Always
          args:
            - "run"
            - "--dnsurl=http://dns-server-ui.__NPH_NAMESPACE:80"
            - "--sm=system-model.__NPH_NAMESPACE:8800"
            - "--zturl=http://localhost:9993"
            - "--queueAddress=broker.__NPH_NAMESPACE:6650"
            - "--debug"
            - "--caCertPath=/nalej/tls-ca-certificate/tls.crt"
            - "--clientCertPath=/nalej/tls-client-certificate/tls.crt"
            - "--skipServerCertValidation=false"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: dev-net-tun
              readOnly: true
              mountPath: /dev/net/tun
            - name: data-network-manager
              mountPath: /var/lib/zerotier-one
            - name: zt-planet
              mountPath: /zt/planet
              readOnly: true
            - name: zt-identity-public
              mountPath: /zt/identity-public
              readOnly: true
            - name: zt-identity-secret
              mountPath: /zt/identity-secret
              readOnly: true
            - name: tls-ca-certificate-volume
              readOnly: true
              mountPath: /nalej/tls-ca-certificate
            - name: tls-client-certificate-volume
              readOnly: true
              mountPath: /nalej/tls-client-certificate
      imagePullSecrets:
        - name: nalej-registry
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: data-network-manager
          persistentVolumeClaim:
            claimName: data-network-manager
        - name: zt-planet
          secret:
            secretName: zt-planet
        - name: zt-identity-public
          secret:
            secretName: zt-identity-public
        - name: zt-identity-secret
          secret:
            secretName: zt-identity-secret
        - name: tls-ca-certificate-volume
          secret:
            secretName: tls-ca-certificate
        - name: tls-client-certificate-volume
          secret:
            secretName: tls-client-certificate
