###
# Application network-manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: network-manager
  name: network-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: network-manager
  template:
    metadata:
      labels:
        cluster: management
        component: network-manager
    spec:
      containers:
      - name: example
        image: nalej/network-manager:VERSION
        env:
          - name: ZT_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: zt-controller-auth
                key: zt-access-token
        imagePullPolicy: IfNotPresent
        args:
          - "run"
          - "--dnsurl"
          - "http://dns-server-ui.nalej:80"
          - "--sm"
          - "system-model.nalej:8800"
          - "--ztaccesstoken"
          - "$(ZT_ACCESS_TOKEN)"
          - "--zturl"
          - "http://zt-controller.nalej:9993"
          - "--debug"
        securityContext:
          runAsUser: 2000