apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cluster: management
    component: network-manager
  name: data-network-manager
  namespace: nalej
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pv-network-manager
